// 瓦片地图枚举
export enum TILE_TYPE_ENUM {
    WALL_LEFT_TOP = "WALL_LEFT_TOP",
    WALL_COLUMN = "WALL_COLUMN",
    CLIFF_LEFT = "CLIFF_LEFT",
    WALL_RIGHT_BOTTOM = "WALL_RIGHT_BOTTOM",
    FLOOR = "FLOOR",
    WALL_ROW = "WALL_ROW",
    CLIFF_CENTER = "CLIFF_CENTER",
    WALL_LEFT_BOTTOM = "WALL_LEFT_BOTTOM",
    WALL_RIGHT_TOP = "WALL_RIGHT_TOP",
    CLIFF_RIGHT = "CLIFF_RIGHT"
}

// 事件枚举
export enum EVENT_ENUM {
    // 下一个关卡
    NEXT_LEVEL = 'NEXT_LEVEL',
    PLAYER_CTRL = 'PLAYER_CTRL',
    PLAYER_MOVE_END = 'PLAYER_MOVE_END',
    PLAYER_BORN = 'PLAYER_BORN',
    ATTACK_PLAYER = 'ATTACK_PLAYER',
    ATTACK_ENEMY = 'ATTACK_ENEMY'
}

// 方向枚举
export enum CONTROLLER_ENUM {
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT',
    TURNLEFT = 'TURNLEFT',
    TURNRIGHT = 'TURNRIGHT'
}

// 定义状态机枚举
export enum FSM_PARAMS_TYPE_ENUM {
    NUMBER = 'NUMBER',
    // 触发类型
    TRIGGER = 'TRIGGER'
}

// 参数名称枚举
export enum PARAMS_NAME_ENUM {
    IDLE = 'IDLE',
    TURNLEFT = 'TURNLEFT',
    TURNRIGHT = 'TURNRIGHT',
    DIRECTION = 'DIRECTION',
    BLOCKFRONT = 'BLOCKFRONT',
    BLOCKBACK = 'BLOCKBACK',
    BLOCKLEFT = 'BLOCKLEFT',
    BLOCKRIGHT = 'BLOCKRIGHT',
    BLOCKTURNLEFT = 'BLOCKTURNLEFT',
    BLOCKTURNRIGHT = 'BLOCKTURNRIGHT',
    ATTACK = 'ATTACK',
    DEATH = 'DEATH',
    AIRDEATH = 'AIRDEATH'
}

// 方向枚举
export enum DIRECTION_ENUM {
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT'
}

export enum ENTITY_STATE_ENUM {
    IDLE = 'IDLE',
    TURNLEFT = 'TURNLEFT',
    TURNRIGHT = 'TURNRIGHT',
    BLOCKFRONT = 'BLOCKFRONT',
    BLOCKBACK = 'BLOCKBACK',
    BLOCKLEFT = 'BLOCKLEFT',
    BLOCKRIGHT = 'BLOCKRIGHT',
    BLOCKTURNLEFT = 'BLOCKTURNLEFT',
    BLOCKTURNRIGHT = 'BLOCKTURNRIGHT',
    ATTACK = 'ATTACK',
    DEATH = 'DEATH',
    AIRDEATH = 'AIRDEATH'
}

// 数据枚举映射 —— 方向
export enum DIRECTION_ORDER_ENUM {
    TOP,
    BOTTOM,
    LEFT,
    RIGHT
}

export enum ENTITY_TYPE_ENUM {
    PLAYER = 'PLAYER'
}
